-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggm4waJoDSuD+GRgE
WNWolsapCt0GAybpusYvbMB1yvqgCgYIKoZIzj0DAQehRANCAARpzKy+Wh5uqygO
jb+De+byv73Qoj5NyZSMHkK7ZXkLdJOVWVW/17D77Y8f/wt9OTXR2HHH+TYBuaGm
Lms53xxC
-----END PRIVATE KEY-----